<?php

namespace AppBundle\Repository;

/**
 * EchelonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EchelonRepository extends \Doctrine\ORM\EntityRepository
{
}
